// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/src/common/types/row/partitioned_tuple_data.cpp>
#include </home/lan/Y_TE/duckdb/src/common/types/row/tuple_data_allocator.cpp>
#include </home/lan/Y_TE/duckdb/src/common/types/row/tuple_data_collection.cpp>
#include </home/lan/Y_TE/duckdb/src/common/types/row/tuple_data_iterator.cpp>
#include </home/lan/Y_TE/duckdb/src/common/types/row/tuple_data_layout.cpp>
#include </home/lan/Y_TE/duckdb/src/common/types/row/tuple_data_scatter_gather.cpp>
#include </home/lan/Y_TE/duckdb/src/common/types/row/tuple_data_segment.cpp>
