// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/src/storage/buffer/buffer_handle.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/buffer/block_handle.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/buffer/block_manager.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/buffer/buffer_pool.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/buffer/buffer_pool_reservation.cpp>
