// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/src/common/exception/binder_exception.cpp>
#include </home/lan/Y_TE/duckdb/src/common/exception/catalog_exception.cpp>
#include </home/lan/Y_TE/duckdb/src/common/exception/conversion_exception.cpp>
#include </home/lan/Y_TE/duckdb/src/common/exception/parser_exception.cpp>
