// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/union/union_extract.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/union/union_value.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/union/union_tag.cpp>
