// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/generic/alias.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/generic/binning.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/generic/cast_to_type.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/generic/can_implicitly_cast.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/generic/current_setting.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/generic/hash.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/generic/least.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/generic/replace_type.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/generic/stats.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/generic/type_functions.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/generic/system_functions.cpp>
