// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/struct/struct_insert.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/struct/struct_update.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/struct/struct_keys.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/scalar/struct/struct_values.cpp>
