// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/src/parser/constraints/check_constraint.cpp>
#include </home/lan/Y_TE/duckdb/src/parser/constraints/not_null_constraint.cpp>
#include </home/lan/Y_TE/duckdb/src/parser/constraints/unique_constraint.cpp>
#include </home/lan/Y_TE/duckdb/src/parser/constraints/foreign_key_constraint.cpp>
