// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/extension/parquet/writer/array_column_writer.cpp>
#include </home/lan/Y_TE/duckdb/extension/parquet/writer/boolean_column_writer.cpp>
#include </home/lan/Y_TE/duckdb/extension/parquet/writer/decimal_column_writer.cpp>
#include </home/lan/Y_TE/duckdb/extension/parquet/writer/enum_column_writer.cpp>
#include </home/lan/Y_TE/duckdb/extension/parquet/writer/list_column_writer.cpp>
#include </home/lan/Y_TE/duckdb/extension/parquet/writer/primitive_column_writer.cpp>
#include </home/lan/Y_TE/duckdb/extension/parquet/writer/struct_column_writer.cpp>
