// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/src/function/scalar/generic/constant_or_null.cpp>
#include </home/lan/Y_TE/duckdb/src/function/scalar/generic/error.cpp>
#include </home/lan/Y_TE/duckdb/src/function/scalar/generic/getvariable.cpp>
