// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/src/storage/statistics/base_statistics.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/statistics/column_statistics.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/statistics/distinct_statistics.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/statistics/array_stats.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/statistics/list_stats.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/statistics/numeric_stats.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/statistics/segment_statistics.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/statistics/string_stats.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/statistics/struct_stats.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/statistics/geometry_stats.cpp>
#include </home/lan/Y_TE/duckdb/src/storage/statistics/variant_stats.cpp>
