// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/extension/core_functions/aggregate/nested/binned_histogram.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/aggregate/nested/list.cpp>
#include </home/lan/Y_TE/duckdb/extension/core_functions/aggregate/nested/histogram.cpp>
