// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/src/common/sort/full_sort.cpp>
#include </home/lan/Y_TE/duckdb/src/common/sort/hashed_sort.cpp>
#include </home/lan/Y_TE/duckdb/src/common/sort/natural_sort.cpp>
#include </home/lan/Y_TE/duckdb/src/common/sort/sort.cpp>
#include </home/lan/Y_TE/duckdb/src/common/sort/sort_strategy.cpp>
#include </home/lan/Y_TE/duckdb/src/common/sort/sorted_run.cpp>
#include </home/lan/Y_TE/duckdb/src/common/sort/sorted_run_merger.cpp>
