// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/extension/parquet/reader/variant/variant_binary_decoder.cpp>
#include </home/lan/Y_TE/duckdb/extension/parquet/reader/variant/variant_shredded_conversion.cpp>
