// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/src/common/adbc/nanoarrow/metadata.cpp>
#include </home/lan/Y_TE/duckdb/src/common/adbc/nanoarrow/schema.cpp>
#include </home/lan/Y_TE/duckdb/src/common/adbc/nanoarrow/allocator.cpp>
#include </home/lan/Y_TE/duckdb/src/common/adbc/nanoarrow/single_batch_array_stream.cpp>
