// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/src/execution/operator/schema/physical_alter.cpp>
#include </home/lan/Y_TE/duckdb/src/execution/operator/schema/physical_attach.cpp>
#include </home/lan/Y_TE/duckdb/src/execution/operator/schema/physical_create_index.cpp>
#include </home/lan/Y_TE/duckdb/src/execution/operator/schema/physical_create_schema.cpp>
#include </home/lan/Y_TE/duckdb/src/execution/operator/schema/physical_create_type.cpp>
#include </home/lan/Y_TE/duckdb/src/execution/operator/schema/physical_create_sequence.cpp>
#include </home/lan/Y_TE/duckdb/src/execution/operator/schema/physical_create_table.cpp>
#include </home/lan/Y_TE/duckdb/src/execution/operator/schema/physical_create_trigger.cpp>
#include </home/lan/Y_TE/duckdb/src/execution/operator/schema/physical_create_view.cpp>
#include </home/lan/Y_TE/duckdb/src/execution/operator/schema/physical_create_function.cpp>
#include </home/lan/Y_TE/duckdb/src/execution/operator/schema/physical_detach.cpp>
#include </home/lan/Y_TE/duckdb/src/execution/operator/schema/physical_drop.cpp>
