// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/src/logging/log_manager.cpp>
#include </home/lan/Y_TE/duckdb/src/logging/log_storage.cpp>
#include </home/lan/Y_TE/duckdb/src/logging/log_types.cpp>
#include </home/lan/Y_TE/duckdb/src/logging/logger.cpp>
#include </home/lan/Y_TE/duckdb/src/logging/logging.cpp>
