// Unity Build generated by CMake
#include </home/lan/Y_TE/duckdb/src/main/secret/secret.cpp>
#include </home/lan/Y_TE/duckdb/src/main/secret/secret_manager.cpp>
#include </home/lan/Y_TE/duckdb/src/main/secret/secret_storage.cpp>
#include </home/lan/Y_TE/duckdb/src/main/secret/default_secrets.cpp>
